version: '3.8'

services:
  core-unit-tests:
    build:
      context: ../../
      dockerfile: infrastructure/images/Dockerfile.core-ci
    command: bin/ci/unit-test.mjs
    depends_on:
      - services-db
    volumes:
      - ${PWD}/translations:/usr/voxelkit/translations
      - ${PWD}/services:/usr/voxelkit/services

  services-db:
    image: mongo:${MONGODB_VERSION}
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
