version: '3.8'

services:
  core-unit-tests:
    build:
      context: ../../
      dockerfile: infrastructure/images/Dockerfile.core-ci
    command: bin/ci/unit-test.mjs
    depends_on:
      - services-db
    volumes:
      - ${PWD}/translations:/usr/voxelkit/translations
      - ${PWD}/services:/usr/voxelkit/services

  services-db:
    image: mongo:${MONGO_VERSION}
    ports:
      - 27017:27017
    logging:
      driver: none
