# syntax=docker.io/docker/dockerfile:1

FROM voxelkit-core

ENV CLOUDSDK_INSTALL_DIR /usr/local/gcloud/

RUN curl -sSL https://sdk.cloud.google.com | bash

ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

RUN cd bin/local && npm ci --ignore-scripts
